Repository ShwetKhatri2001/Swetify-Music, pull requests merged in 2023-12, with the labels that each got.

#21 Changed Color of NavBar text
  index.html
  swetify.css
Labels: enhancement, Codepeak23, easy

#25 The 'like' functionality added
  icons/likeAfter.png
  icons/likeBefore.png
  index.html
  script.js
  swetify.css
  swetify.js
Labels: feature, Codepeak23, hard

#31 adding contriubtion.md
  CONTRIBUTION.md
Labels: documentation, Codepeak23, easy

#42 Fixes Issue #39: JavaScript and CSS Code Optimization and some improvements!
  index.html
  script.js
  swetify.css
Labels: enhancement, Codepeak23, easy, BONUS 🎁
